apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
spec:
  type: NodePort        # optional, add if you want external access via NodePort
  selector:
    app: online-shop
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080     # optional: set a fixed NodePort if needed

