apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
spec:
  type: NodePort
  selector:
    app: online-shop
  ports:
  - port: 3000        # ClusterIP port
    targetPort: 3000  # Container port
    nodePort: 30080   # NodePort to access externally

