apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
