apiVersion: v1
kind: Service
metadata:
  name: online-shop-service
  namespace: default
spec:
  selector:
    app: online-shop
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort
